on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: iliiadenisov/cpp-26-playground:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive 
      - name: Build
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Test
        run: |
          cd build
          ./tests